In [1]:
import numpy as np

In [7]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(arr.ndim)
print(arr.shape)



5.0
5.0
3.1622776601683795
10.0
1
(11,)


In [14]:
mat = np.matrix('1, 2, 3; 4, 5, 6; 7, 8, 9')
print(mat)
for row in mat:
    for element in row:
        print(element)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


In [16]:
matA = np.matrix('1, 2, 3; 4, 5, 6; 7, 8, 9')
matB = np.matrix('1, 2, 3; 4, 5, 6; 7, 8, 9')
matC = matA + matB
print(matC)
matD = matA * matB
print(matD)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [17]:
print(np.pi)
print(np.e)
angle = np.pi/4
print(np.sin(angle))
print(np.cos(angle))
print(np.tan(angle))


3.141592653589793
2.718281828459045
0.7071067811865476
0.7071067811865476
0.9999999999999999


In [20]:
x = np.array([[1, 2, 3, 4], [5, 6, 7 ,8]])
print(x[0, 1])
print(x[:, 2])
for row in x:
    for y in row:
        print(y)
print(x[:,::2])


2
[3 7]
1
2
3
4
5
6
7
8
[[1 3]
 [5 7]]


In [27]:
y = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]])
print(y[:,0,:])
print(y.dtype)
print(y.ndim)
print(len(y.shape))
print(type(y))
d_0 = np.array(42)

[[ 1  2  3  4]
 [ 9 10 11 12]]
int32
3
3
<class 'numpy.ndarray'>


In [29]:
z = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(z[4:])
print(z[:4])
print(z[:4:2])
print(z[-3:])

[5 6 7 8]
[1 2 3 4]
[1 3]
[6 7 8]
